#!/usr/bin/env bash
echo -n "Enter Dir name: "
read dirx
if [ -d ./$dirx/ ]; then
echo -n "New Pass: "
read spx

zip --password $spx -r $dirx.zip $dirx
rm -rf $dirx/
else 
unzip $dirx.zip
rm -rf $dirx.zip
fi

